-- Add migration script here
-- 기존 테이블 삭제 (필요 시 주석 제거 후 실행)
-- DROP TABLE IF EXISTS RESERVATION;
-- DROP TABLE IF EXISTS CONTENT_SCHEDULE;
-- DROP TABLE IF EXISTS CONTENTS;
-- 예약 테이블
CREATE TABLE RESERVATION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(6)  NOT NULL,
    content_schedule_id BIGINT UNSIGNED NOT NULL,
    reserved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('PENDING', 'CONFIRMED', 'CANCELLED') DEFAULT 'PENDING',
    use_at BOOLEAN NOT NULL,
    ad_cnt INT,
    cd_cnt INT,  
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (content_schedule_id) REFERENCES CONTENT_SCHEDULES(id) ON DELETE CASCADE
);
